development:
  adapter: postgresql
  encoding: unicode
  database: code_challenge_development
  pool: 5
  username: reedns
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: code_challenge_test
  pool: 5
  username: reedns
  password:
